name: Get Issues After Latest Release

on:
  workflow_dispatch:
    inputs:
      repository:
        required: true
        description: 'MrMeta/fooddiary'
      baseRef:
        required: true
        description: 'master, main, live ...'
      hotfix:
        default: false
        type: boolean

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        repository: ${{ github.event.inputs.repository }}
        ref: ${{ github.event.inputs.baseRef }}
        token: ${{ secrets.GLOBAL_GITHUB_TOKEN }}
        path: app
    - name: Test
      working-directory: ../app
      run: echo `git log --oneline -1`
    - name: input condition test
      run: echo "${{ github.event.inputs.hotfix == true && 'hotfix' }}"

