name: Add link to document PR

on:
  pull_request:
    types: [opened, edited]

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
    - name: My first step
      if: ${{ github.event_name == 'pull_request' }}
      run: echo ${{ github.event.number }} && echo ${{ github.event.pull_request.title }}
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.number }}
        body: hehe :scroll: