name: "Print inputted value"

on:
  schedule: 0 0 * * *
  workflow_dispatch:
    inputs:
      value:
        description: 'Input any value'
        default: 'identity'

step:
  - name: 'echo value'
    run: echo {{ github.events.inputs.value }}
