name: Print inputted value

on:
  push:
    - main
  workflow_dispatch:
    inputs:
      value:
        description: 'Input any value'
        default: 'identity'

jobs:
  echo:
    name: Echo value
    runs-on: ubuntu-latest

    steps:
      - name: 'echo value'
        run: echo ${{ github.events.inputs.value }}
