name: Print inputted value

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
    inputs:
      value:
        description: 'Input any value'
        default: 'identity'

step:
  echo:
    name: Echo value
    runs-on: ubuntu-latest

    steps:
      - name: 'echo value'
        run: echo {{ github.events.inputs.value }}
